### ISSUE TITLE
extauth script has exitted abruptly 

### ISSUE THREAD

**Issue by umarniz** [senseobservationsystems/ejabberd#8]
@fichie23 Lots of these errors also found in the logs:

```
2018-05-08 09:50:04.961 [critical] <0.15904.3>@extauth:loop:137 extauth script has exitted abruptly with reason 'normal'
```

**Comment by fichie23** [comment]
I will investigate this

**Comment by fichie23** [comment]
This happened because our external auth using https://github.com/senseobservationsystems/django-ejabberd-bridge not running forever because of exception, so `django-ejabberd-bridge` it will always exitted, so i do the refactor [here](https://github.com/senseobservationsystems/django-ejabberd-bridge/pull/6) to fix this
